name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update date in README
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')
          sed -i "s|<!--DATE-->|$DATE|g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "chore: update README date to $DATE" || exit 0
          git push
